language: rust
rust:
  - 1.48.0
python:
  - 3.9
install:
  - sudo pip3 install nose
  - rustup install nightly
  - rustup component add rustfmt-preview --toolchain nightly
script: make travis
sudo: required
