language: rust
rust:
  - 1.61.0
python:
  - 3.9
before_install:
  - sudo apt-get update
  - sudo apt-get install python3 python3-pip
install:
  - sudo pip3 install nose
  - rustup install nightly
  - rustup component add rustfmt-preview --toolchain nightly
script: make travis
sudo: required
