#define TOKEN_EOI                     0
#define TOKEN_ANY                     1
#define TOKEN_COMMA                   2
#define TOKEN_DOUBLEDASH              3
#define TOKEN_ELSE                    4
#define TOKEN_HASHTAG                 5
#define TOKEN_ID                      6
#define TOKEN_INT                     7
#define TOKEN_PLUS                    8
#define TOKEN_SLASH                   9
#define TOKEN_StrLit                  10
#define TOKEN_TYPE_ID                 11
#define TOKEN_ASSIGN                  12
#define TOKEN_BLOCKARROW              13
#define TOKEN_RETURN                  14
#define TOKEN_OR                      15
#define TOKEN_XOR                     16
#define TOKEN_AND                     17
#define TOKEN_ConcatNewline           18
#define TOKEN_NOT                     19
#define TOKEN_EQ                      20
#define TOKEN_NEQ                     21
#define TOKEN_GT                      22
#define TOKEN_GTEQ                    23
#define TOKEN_LT                      24
#define TOKEN_LTEQ                    25
#define TOKEN_MINUS                   26
#define TOKEN_TIMES                   27
#define TOKEN_MOD                     28
#define TOKEN_DOLLAR                  29
#define TOKEN_DOT                     30
#define TOKEN_LPAREN                  31
#define TOKEN_RPAREN                  32
#define TOKEN_STRUCT                  33
#define TOKEN_COLON                   34
#define TOKEN_FAIL                    35
#define TOKEN_FAILED                  36
#define TOKEN_Let                     37
#define TOKEN_Fork                    38
#define TOKEN_Func                    39
#define TOKEN_PARENCALL               40
#define TOKEN_TYPE_INT                41
#define TOKEN_TYPE_STR                42
#define TOKEN_TYPE_BOOL               43
#define TOKEN_TYPE_VOID               44
#define TOKEN_PS                      45
#define TOKEN_MACRO                   46
#define TOKEN_IF                      47
#define TOKEN_PIPE                    48
#define TOKEN_CASE                    49
#define TOKEN_MATCH                   50
#define TOKEN_True                    51
#define TOKEN_False                   52
#define TOKEN_UNDERSCORE              53
#define TOKEN_NEGATE                  54
#define TOKEN_VOID                    55
#define TOKEN_DollarQuestion          56
#define TOKEN_SquareL                 57
#define TOKEN_SquareR                 58
#define TOKEN_StrOpen                 59
#define TOKEN_StrClose                60
