#define TOKEN_EOI                     0
#define TOKEN_ANY                     1
#define TOKEN_COLON                   2
#define TOKEN_COMMA                   3
#define TOKEN_DOUBLEDASH              4
#define TOKEN_ELSE                    5
#define TOKEN_HASHTAG                 6
#define TOKEN_ID                      7
#define TOKEN_INT                     8
#define TOKEN_Let                     9
#define TOKEN_PLUS                    10
#define TOKEN_SEMICOLON               11
#define TOKEN_SLASH                   12
#define TOKEN_SquareL                 13
#define TOKEN_SquareR                 14
#define TOKEN_StrLit                  15
#define TOKEN_TYPE_ID                 16
#define TOKEN_ASSIGN                  17
#define TOKEN_BLOCKARROW              18
#define TOKEN_RETURN                  19
#define TOKEN_OR                      20
#define TOKEN_XOR                     21
#define TOKEN_AND                     22
#define TOKEN_ConcatNewline           23
#define TOKEN_NOT                     24
#define TOKEN_EQ                      25
#define TOKEN_NEQ                     26
#define TOKEN_GT                      27
#define TOKEN_GTEQ                    28
#define TOKEN_LT                      29
#define TOKEN_LTEQ                    30
#define TOKEN_MINUS                   31
#define TOKEN_TIMES                   32
#define TOKEN_MOD                     33
#define TOKEN_DOLLAR                  34
#define TOKEN_DOT                     35
#define TOKEN_LPAREN                  36
#define TOKEN_RPAREN                  37
#define TOKEN_STRUCT                  38
#define TOKEN_FAIL                    39
#define TOKEN_FAILED                  40
#define TOKEN_Fork                    41
#define TOKEN_Func                    42
#define TOKEN_PARENCALL               43
#define TOKEN_TYPE_INT                44
#define TOKEN_TYPE_STR                45
#define TOKEN_TYPE_HASHTAG            46
#define TOKEN_TYPE_BOOL               47
#define TOKEN_TYPE_VOID               48
#define TOKEN_PS                      49
#define TOKEN_MACRO                   50
#define TOKEN_IF                      51
#define TOKEN_PIPE                    52
#define TOKEN_CASE                    53
#define TOKEN_MATCH                   54
#define TOKEN_True                    55
#define TOKEN_False                   56
#define TOKEN_UNDERSCORE              57
#define TOKEN_NEGATE                  58
#define TOKEN_VOID                    59
#define TOKEN_DollarQuestion          60
#define TOKEN_StrOpen                 61
#define TOKEN_StrClose                62
