#define TOKEN_EOI                     0
#define TOKEN_ANY                     1
#define TOKEN_AND                     2
#define TOKEN_BLOCKARROW              3
#define TOKEN_COLON                   4
#define TOKEN_COMMA                   5
#define TOKEN_ConcatNewline           6
#define TOKEN_DBLCOLON                7
#define TOKEN_DOUBLEDASH              8
#define TOKEN_ELSE                    9
#define TOKEN_EQ                      10
#define TOKEN_EQ1                     11
#define TOKEN_Fork                    12
#define TOKEN_GT                      13
#define TOKEN_GTEQ                    14
#define TOKEN_HASHTAG                 15
#define TOKEN_ID                      16
#define TOKEN_IF                      17
#define TOKEN_IMPORT                  18
#define TOKEN_INT                     19
#define TOKEN_Let                     20
#define TOKEN_LT                      21
#define TOKEN_LTEQ                    22
#define TOKEN_MATCH                   23
#define TOKEN_MINUS                   24
#define TOKEN_MOD                     25
#define TOKEN_NEGATE                  26
#define TOKEN_NEQ                     27
#define TOKEN_NOT                     28
#define TOKEN_OR                      29
#define TOKEN_LPAREN                  30
#define TOKEN_RPAREN                  31
#define TOKEN_PARENCALL               32
#define TOKEN_PIPE                    33
#define TOKEN_PLUS                    34
#define TOKEN_RETURN                  35
#define TOKEN_SEMICOLON               36
#define TOKEN_SLASH                   37
#define TOKEN_SquareL                 38
#define TOKEN_SquareR                 39
#define TOKEN_StrLit                  40
#define TOKEN_StrOpen                 41
#define TOKEN_STRUCT                  42
#define TOKEN_TIMES                   43
#define TOKEN_TYPE_VAR                44
#define TOKEN_XOR                     45
#define TOKEN_ASSIGN                  46
#define TOKEN_DOLLAR                  47
#define TOKEN_DOT                     48
#define TOKEN_FAILED                  49
#define TOKEN_Func                    50
#define TOKEN_RUSTBLOCK               51
#define TOKEN_TYPE_INT                52
#define TOKEN_TYPE_STR                53
#define TOKEN_TYPE_HASHTAG            54
#define TOKEN_TYPE_BOOL               55
#define TOKEN_TYPE_VOID               56
#define TOKEN_MACRO                   57
#define TOKEN_VOID                    58
#define TOKEN_DollarQuestion          59
#define TOKEN_True                    60
#define TOKEN_False                   61
#define TOKEN_UNDERSCORE              62
#define TOKEN_StrClose                63
