
digit = { '0'..'9' }
float = @{ digit+ ~ "." ~ digit+ }
int = @{ digit+ }
number = _{ float | int }

and = { "and" }
or = { "or" }

infix_op = _{
    "+" | "-" | "*" | "/" | "mod"
    | and | or
    | "<" | "<=" | "==" | "!=" | ">=" | ">"
}

WHITESPACE = _{ " " }

id = @{ LETTER ~ ( LETTER | NUMBER )* }

term = _{ id | number }

infix_expr = { term ~ (infix_op ~ expr)+ }

expr = {
    infix_expr
    | term
}
