name: make T

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: xoviat/actions-pytest@0.1-alpha2
    - name: Build
      run: cargo build --verbose
    - name: Run integration tests
      run: make T
