name: make T

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - uses: actions/checkout@v3
    - run: pip install pytest
    - name: Build
      run: cargo build --verbose
    - name: Run integration tests
      run: make T
